sonia_page:
    resource: "@SoniaPageBundle/Resources/config/routing.yml"
    prefix:   /

acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

angelescuangelescu:
    resource: "@AngelescuangelescuBundle/Resources/config/routing.yml"
    prefix:   /

tudor_pag_pers:
    resource: "@TudorPagPersBundle/Resources/config/routing.yml"
    prefix:   /

